### ISSUE TITLE
Can you update dependency to flutter_slidable 1.1.0?

### ISSUE THREAD

**Issue by saelco** [fabio21/open_document#1]
I can't use flutter_slidable 1.1.0 because got error:
Because open_document 1.0.3+1 depends on flutter_slidable ^0.6.0 and no versions of open_document match >1.0.3+1 <2.0.0, open_document ^1.0.3+1 requires flutter_slidable ^0.6.0.
So, because myapp depends on both open_document ^1.0.3+1 and flutter_slidable ^1.1.0, version solving failed.
pub get failed (1; So, because myapp depends on both open_document ^1.0.3+1 and flutter_slidable ^1.1.0, version solving failed.)

**Comment by fabio21** [comment]
update version flutter_slidable 1.2.0
