### ISSUE TITLE
Can't add flutter_localization package to flutter projects cause open_document depends on "intl: ^0.17.0"

### ISSUE THREAD

**Issue by Gantushig77** [fabio21/open_document#10]
flutter_localization package is the recommended way to add localization features by the flutter team itself. Since every version of the package depends on the "intl" package with version 0.18.0, package version solving cannot be done with the open_document package. In order to fix the package version-solving issue, please upgrade the open_document package with the latest version of the "intl" package.

**Comment by fabio21** [comment]
new version

**Comment by wilpar** [comment]
and again please...  0.19

Please see
https://github.com/fabio21/open_document/pull/15
