### ISSUE TITLE
Any plan to support share_plus 4.0.3?

### ISSUE THREAD

**Issue by saelco** [fabio21/open_document#2]
Because open_document 1.0.4 depends on share_plus ^3.0.2 and no versions of open_document match >1.0.4 <2.0.0, open_document ^1.0.4 requires share_plus ^3.0.2.
So, because smartkit depends on both share_plus ^4.0.3 and open_document ^1.0.4, version solving failed.

**Comment by mellowcello77** [comment]
This package needs to support at least share_plus 4.0.4 now. Apps do not compile with lower version of share_plus and gives error - "Flutter : Type mismatch: inferred type is String? but String was expected" which is fixed in 4.0.4. Sot his package just breaks the app now.

**Comment by fabio21** [comment]
update flutter 3.0 and share_plus
