### ISSUE TITLE
share_plus lower than 4.0.4 breaks app

### ISSUE THREAD

**Issue by mellowcello77** [fabio21/open_document#3]
The package needs to support at least share_plus 4.0.4 now. Android apps do not compile with the current version of share_plus and gives error - "Flutter : Type mismatch: inferred type is String? but String was expected" which is fixed in share_plus 4.0.4.

**Comment by xiaodusx1** [comment]
The same problem

**Comment by Rohit-ChauhanRC** [comment]
The same problem

**Comment by bermanapps** [comment]
Any updates with this? Same problem
