### ISSUE TITLE
Unhandled Exception: Instance of 'OpenDocumentException'

### ISSUE THREAD

**Issue by k1ycee** [fabio21/open_document#6]
I get this error anytime I try to open a pdf document.

Something about the filepath not being correct.

`E/MethodChannel#open_document(25548): Failed to handle method call
E/MethodChannel#open_document(25548): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.itojume.fileprovider
E/MethodChannel#open_document(25548):   at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)
E/MethodChannel#open_document(25548):   at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
E/MethodChannel#open_document(25548):   at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)
E/MethodChannel#open_document(25548):   at com.example.open_document.OpenDocumentPlugin.openDocument(OpenDocumentPlugin.kt:93)
E/MethodChannel#open_document(25548):   at com.example.open_document.OpenDocumentPlugin.onMethodCall(OpenDocumentPlugin.kt:71)
E/MethodChannel#open_document(25548):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#open_document(25548):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#open_document(25548):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#open_document(25548):   at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#open_document(25548):   at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#open_document(25548):   at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#open_document(25548):   at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#open_document(25548):   at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#open_document(25548):   at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#open_document(25548):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#open_document(25548):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#open_document(25548):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (25548): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Instance of 'OpenDocumentException'
E/flutter (25548): #0      OpenDocument.openDocument (package:open_document/open_document.dart:16:7)
E/flutter (25548): <asynchronous suspension>
E/flutter (25548): #1      PDFUtility.savePdfFile (package:itojume/utils/pdf/pdf_util.dart:20:5)
E/flutter (25548): <asynchronous suspension>
E/flutter (25548): `

**Comment by fabio21** [comment]
Can you give me an example of how you are using

**Comment by Zedem-source** [comment]
I also have this error when I go to open a pdf
java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.proprietaire.fileprovider

**Comment by fabio21** [comment]
please follow the main screen README guidelines
