### ISSUE TITLE
error: resource android:attr/lStar not found

### ISSUE THREAD

**Issue by Asad93915** [fabio21/open_document#8]
I am using this package in my project it's working perfect in debug mode but while in profile mode and when I generate apk it shows error like this
Execution failed for task ':open_document:verifyProfileResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\absol\.gradle\caches\transforms-3\5e083c06c9925c2309f02468fc66e376\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by fabio21** [comment]
clear gradle cache 
https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable

**Comment by freddirkse** [comment]
I am having this exact same issue. To test, I started a brand new default Flutter project, added open_document ^1.0.5 to pubspec.yaml. Debug works fine, but building for release crashes with the same error: 

Execution failed for task ':open_document:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\[my_user_directory]\.gradle\caches\transforms-3\0abb5ac90011bd27da412ddabf5e09c1\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

I remove open_document and the release builds without issue.

I've cleared all of my caches and indexes, flutter clean, and even specifically disabled gradle cache in my gradle properties: org.gradle.caching=false. Same results. 

My environment:
Android Studio Dolphin | 2021.3.1 Patch 1
Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19043.2006]
kotlin_version = '1.7.20'
com.android.tools.build:gradle:7.1.3 (also tried 7.3.0)
compileSdkVersion = 31
minSdkVersion = 16
targetSdkVersion = 31

**Comment by roshdiAlMajzoub** [comment]
anyone has solved the problem?
i need your help

**Comment by roshdiAlMajzoub** [comment]
> 

how u solved it?

**Comment by roshdiAlMajzoub** [comment]
You can use OpenFile.open(filePath)
I hope this solves your problem.

**Comment by freddirkse** [comment]
> You can use OpenFile.open(filePath) I hope this solves your problem.

Are you using the open_file plugin instead of open_document?
If this doesn't get resolved shortly I'll give that a shot, thank you.

**Comment by fabio21** [comment]
you have a file created in your re--> values ​​-> values.xml

in debug and main

\res\values\values.xml

you set up AndroidManifest.xml in main or so in debug
->> android ->> app ->> src ->> debug | main --> AndroidManifest.xml config

inside the re folder you created the xml folder and the file provider_paths.xml
->> res ->> xml -->> provider_paths.xml 

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="external_files"
        path="." />
</paths>

**Comment by freddirkse** [comment]
> you have a file created in your re--> values ​​-> values.xml
> 
> in debug and main
> 
> \res\values\values.xml
> 
> you set up AndroidManifest.xml in main or so in debug ->> android ->> app ->> src ->> debug | main --> AndroidManifest.xml config

I have a res\values folder, but only a styles.xml file in that folder. 
Should there be some other folder or file in there? 

> inside the re folder you created the xml folder and the file provider_paths.xml ->> res ->> xml -->> provider_paths.xml
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <paths>
>     <external-path
>         name="external_files"
>         path="." />
> </paths>
> ```
Yes, xml -> provider_paths.xml is there and referenced in AndroidManifest.xml config. This is for path provider and is working fine.

**Comment by fabio21** [comment]
https://stackoverflow.com/questions/69041630/android-build-error-lstar-not-found

**Comment by freddirkse** [comment]
> https://stackoverflow.com/questions/69041630/android-build-error-lstar-not-found

Oh, right - that file is created by gradle when you build, it's not a core configuration file we can/should edit. 
When the open_document plugin is included, it adds the lstar configuration to the values.xml file and build fails. When open_document is removed from the project, the lstar entry is not in the values.xml and the build completes successfully. 

I already went through everything in that stackoverflow thread. This is something with the open_document plugin.

**Comment by fabio21** [comment]
you are compiling apk by flutter va command in your project by android studio ,
open android folder in android studio

wait for the project to load and go to
Build -> Generate Signed Bundle

I do it this way it works

**Comment by fabio21** [comment]
fix new version 1.0.6
